

/****** Object:  Table [dbo].[ANM_STATUS_COMPRAS_PA_MOV]    Script Date: 01/04/2016 13:52:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ANM_STATUS_COMPRAS_MP_MOV](
	[ID_REGISTRO] [int] IDENTITY(1,1) NOT NULL,
	[PEDIDO] [varchar](8) NOT NULL,
	[ANM_STATUS_ALMOX] [varchar](25) NOT NULL,
	[DATA_ALTERACAO] [datetime] NOT NULL,
	[DATA_SEPARA] [datetime] NULL,
	[USUARIO_LINX] [varchar](40) NOT NULL,
	[USUARIO_WINDOWS] [varchar](40) NOT NULL,
	[NOME_MAQUINA] [varchar](40) NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
	[CHAVE_ID] [int] NULL,
	[CHAVE_SAI_MAT] [char](8) NULL,
 CONSTRAINT [PK_ANM_STATUS_COMPRAS_MP_MOV] PRIMARY KEY CLUSTERED 
(
	[ID_REGISTRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


