* Criação *********************************************************************************************************** 
* PROGRAMADOR(A).:  Julio Cesar                                                                                     *
* DATA...........:  01-03-2014                                                                                      *
* HORÁRIO........:                                                                                                  *
********************************************************************************************************************* 
* CLIENTE..:                                                                                               			*
* OBJETIVO.: 					                    																*
********************************************************************************************************************* 

* Alteração ********************************************************************************************************* 
* PROGRAMADOR(A).:                                                                                                  *
* DATA...........:                                                                                                  *
* HORÁRIO........:                                                                                                  *
********************************************************************************************************************* 
* CLIENTE..:                                                                                                        *
* OBJETIVO.:                                                                                                        *
********************************************************************************************************************* 


********************************************************************************************************************* 
*- Programa Base de Criação de Objeto de Entrada                                                                    *
********************************************************************************************************************* 
*- O programa deve ser texto com o nome = OBJ_xxxxxx.prg onde x=numero da tela                                      *
*- Este arquivo deve ser colocado no diretorio \Linx_sql\Linx\Exclusivos                                            *
********************************************************************************************************************* 
*- Existem 2 parametros que influem nos objetos de Entrada:                                                         *
*  utiliza_objeto_entrada = .f. desliga os objetos de entrada para testar telas sem os mesmos                       *
*  mostra_nome_obj = .t. mostra o nome dos objetos no tooltip em tempo de execução para facilitar o desenvolvimento *
********************************************************************************************************************* 
* - Atencao !!!!!!!!!!!														                                        *
* - Toda vez que houver qualquer alteracao no PRG deve-se apagar o arquivo FXP                                      *
********************************************************************************************************************* 

define class obj_entrada as custom
	*- Nome do metodo/função que os objetos linx vão chamar.

	procedure metodo_usuario
		*- Parametros do metodo:
		*- Xmetodo= nome do metodo
		*- Xobjeto= variavel com a referencia ao objeto
		*- Xnome_obj  = nome do objeto
		lparam xmetodo, xobjeto ,xnome_obj
		
		******************** Metodos chamados pelo FORMSET
		*	USR_INIT  												=> NA INICIALIZACAO DA TELA 
		*	USR_ALTER_BEFORE  -> Return .f. Para o Metodo 			=> ANTES DA ALTERACAO ,AO CLICKAR ANTES DE LIBERAR OS CAMPOS
		*	USR_ALTER_AFTER 										=> APOS LIBERAR OS CAMPOS PARA INCLUSAO   
		*	USR_INCLUDE_AFTER 										=> APOS LIBERAR OS CAMPOS PARA INCLUSAO
		*	USR_SEARCH_BEFORE -> Return .f. Para o Metodo PESQUISA	=> ANTES DE FAZER A PESQUISA NO BANCO
		*	USR_SEARCH_AFTER										=> APOS FAZER A PESQUISA NO BANCO
		*	USR_CLEAN_AFTER 										=> APOS LIMPAR A TELA 
		*	USR_REFRESH                                             => 
		*	USR_SAVE_BEFORE   -> Return .f. Para o Metodo 			=> SALVAR ANTES DE JOGAR INFORMACOES NO BANCO
		*	USR_SAVE_AFTER                                          => APOS SALVAR AS INFORMACOES    NO BANCO
		*	USR_ITEN_DELETE_BEFORE -> Return .f. Para o Metodo 		=> ANTES DE EXCLUIR ITEN NA TABELA FILHA '+'
		*	USR_ITEN_DELETE_AFTER                                   => APOS DELETAR UM ITEM NA TABELA FILHA '-' 
		*	USR_ITEN_INCLUDE_BEFORE -> Return .f. Para o Metodo 	=> ANTES DE INCLUIR ITEM NA TABELA FILHA
		*	USR_ITEN_INCLUDE_AFTER									=> APOS INCLUIR ITEM NA TABELA FILHA 
		*
		***************** Metodos que ocorrem dentro da Transaction do Banco de Dados
		*	USR_TRIGGER_AFTER ->Return .f. Para o Salvamento e da Rollback ANTES DE EXECUTAR UMA TRIGGER
		*	USR_TRIGGER_BEFORE ->Return .f. Para o Salvamento e da Rollback


		******************** Metodo chamado pelos Objetos na Validação
		*   USR_VALID -> Return .f. Não deixa o Usuario sair do objeto.

		******************** Metodo chamado pelos PageFrames
		*   USR_ACTIVE_PAGE -> Return .f. Para o Metodo.

		*- Inicio dos procedimentos do Usuario
		*- Testando qual o metodo que esta chamando o metodo entrada

		*=messagebox( 'Metodo '+ UPPER(xmetodo) + ' Nome Objeto ' + upper(xnome_obj) )

			do case
				
				case upper(xmetodo) == 'USR_INIT'	
				
					xalias=alias()
					
						xVersao = '01.1'
						f_update("update transacoes set versao_liberada = ?xVersao where control_sistema like '"+right(ALLTRIM(Thisformset.p_controle_sistema),6)+"%' and versao_liberada <> ?xVersao ")
						f_select("Select valor_atual from parametros where parametro = 'ver_hotfix'","CurVersaoLinx")
						WAIT WINDOW "Versão: "+allt(CurVersaoLinx.valor_atual)+"."+xVersao NOWAIT 	
						
						Thisformset.lx_form1.AddObject("btn_exportar","btn_exportar")
						
						Thisformset.L_limpa()	
					
					if	!f_vazio(xalias)	
						sele &xalias 
					endif
					
				case upper(xmetodo) == 'USR_REFRESH'
					if type("Thisformset.lx_form1.btn_exportar")<>"U"
						if thisformset.p_tool_status $ 'IAL'
							Thisformset.lx_form1.btn_exportar.enabled=.F.
						else
							Thisformset.lx_form1.btn_exportar.enabled=.T.
						endif				
					endif	
				
				
				
									
				otherwise
				return .t.				
			endcase

	
	endproc
ENDDEFINE
**************************************************
*-- Class:        btn_exportar (e:\linx_sql_fontecompleta\class pessoal\btn_exportar.vcx)
*-- ParentClass:  botao (e:\linx spk 2018 novo\exclusivos\lx_class.vcx)
*-- BaseClass:    commandbutton
*-- Time Stamp:   07/25/18 08:46:12 AM
*
DEFINE CLASS btn_exportar AS botao


	Top = 58
	Left = 593
	Height = 27
	Width = 101
	Caption = "Exportar Excel"
	Name = "btn_exportar"
	Visible = .T.

	PROCEDURE Click
		if thisformset.p_tool_status = "P"
			f_wait("AGUARDE, EXPORTANDO PARA EXCEL !")
			Sele v_ctb_excecao_imposto_00
			Go Top 
			
			COPY TO c:\temp\Excecao_Imposto_Capa.xls XLS

			***** Novo ******
			TEXT TO xExcecaoItem TEXTMERGE NOSHOW 
				SELECT CTB_EXCECAO_IMPOSTO_ITEM.ID_EXCECAO_IMPOSTO, 
				   CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO, CTB_LX_IMPOSTO_TIPO.IMPOSTO,
				   CTB_EXCECAO_IMPOSTO_ITEM.PORCENT_REDUCAO_DE_BASE, 
				   CTB_EXCECAO_IMPOSTO_ITEM.TAXA_IMPOSTO, 
				   CTB_EXCECAO_IMPOSTO_ITEM.PORC_RECUPERACAO,
				   CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.INDICA_REC_ALIQUOTA_BASE = 'A' THEN 'A - APLICAR % DE RECUPERAÇÃO NA ALÍQUOTA' 
						WHEN CTB_EXCECAO_IMPOSTO_ITEM.INDICA_REC_ALIQUOTA_BASE = 'B' THEN 'B - APLICAR % DE RECUPERAÇÃO NA BASE'
						ELSE CTB_EXCECAO_IMPOSTO_ITEM.INDICA_REC_ALIQUOTA_BASE
						END AS PORC_RECUPERACAO_NA_BASE_OU_ALIQUOTA,
				   CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.AGREGA_APOS_DESCONTO = 1 THEN 'S' ELSE 'N' END AS AGREGA_APOS_DESCONTO,
				   CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.AGREGA_APOS_ENCARGO  = 1 THEN 'S' ELSE 'N' END AS AGREGA_APOS_ENCARGO,
				   CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.INCIDENCIA = 1 THEN '1 - AGREGAR AO VALOR TOTAL DA NOTA'
						WHEN CTB_EXCECAO_IMPOSTO_ITEM.INCIDENCIA = 2 THEN '2 - DESCONTAR DO VALOR TOTAL DA NOTA'
						WHEN CTB_EXCECAO_IMPOSTO_ITEM.INCIDENCIA = 3 THEN '3 - DESTACAR VALOR DO IMPOSTO'
						WHEN CTB_EXCECAO_IMPOSTO_ITEM.INCIDENCIA = 4 THEN '4 - DESEMBUTIR E AGREGAR AO VALOR DO IMPOSTO'
						WHEN CTB_EXCECAO_IMPOSTO_ITEM.INCIDENCIA = 5 THEN '5 - EMBUTIR E DESTACAR O VALOR DO IMPOSTO'
						WHEN CTB_EXCECAO_IMPOSTO_ITEM.INCIDENCIA = 6 THEN '6 - AGREGAR SOMENTE NO TOTAL DA NF (IPI-E e ICMS-SN/ST Devolução)'
						WHEN CTB_EXCECAO_IMPOSTO_ITEM.INCIDENCIA = 7 THEN '7 - NÃO AGREGAR AO TOTAL DA NOTA - (ICMS CM - Cartilha da Mota)'
					ELSE CONVERT(CHAR(2),CTB_EXCECAO_IMPOSTO_ITEM.INCIDENCIA) END AS INCIDENCIA,
					CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.ISENTO_OU_OUTROS = 'I' THEN 'I - ISENTO'
						 WHEN CTB_EXCECAO_IMPOSTO_ITEM.ISENTO_OU_OUTROS = 'O' THEN 'O - OUTROS'
						 WHEN CTB_EXCECAO_IMPOSTO_ITEM.ISENTO_OU_OUTROS = 'N' THEN 'N - NÃO TRIBUTADO'
						 WHEN CTB_EXCECAO_IMPOSTO_ITEM.ISENTO_OU_OUTROS = 'S' THEN 'S - COM SUSPENSÃO'
						 WHEN CTB_EXCECAO_IMPOSTO_ITEM.ISENTO_OU_OUTROS = 'D' THEN 'D - COM DIFERIMENTO'
						 WHEN CTB_EXCECAO_IMPOSTO_ITEM.ISENTO_OU_OUTROS = 'X' THEN 'X - NÃO CONSTAR'
						 WHEN CTB_EXCECAO_IMPOSTO_ITEM.ISENTO_OU_OUTROS = 'Z' THEN 'Z - CONSTAR APENAS VALOR CONTÁBIL'
				     ELSE CONVERT(CHAR(2),CTB_EXCECAO_IMPOSTO_ITEM.ISENTO_OU_OUTROS) END AS ISENTO_OU_OUTROS,

					 CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '00' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 2 then '00 - ENTRADA COM RECUPERAÇÃO DE CRÉDITO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '01' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 2 then '01 - ENTRADA TRIBUTADA COM ALÍQUOTA ZERO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '02' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 2 then '02 - ENTRADA ISENTA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '03' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 2 then '03 - ENTRADA NÃO-TRIBUTADA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '04' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 2 then '04 - ENTRADA IMUNE'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '05' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 2 then '05 - ENTRADA COM SUSPENSÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '49' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 2 then '49 - OUTRAS ENTRADAS' 
						  
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '01' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '01 - OPERAÇÃO TRIBUTÁVEL COM ALÍQUOTA BÁSICA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '02' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '02 - OPERAÇÃO TRIBUTÁVEL COM ALÍQUOTA DIFERENCIADA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '03' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '03 - OPERAÇÃO TRIBUTÁVEL COM ALÍQUOTA POR UNIDADE DE MEDIDA DE PRODUTO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '04' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '04 - OPERAÇÃO TRIBUTÁVEL MONOFÁSICA - REVENDA A ALÍQUOTA ZERO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '05' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '05 - OPERAÇÃO TRIBUTÁVEL POR SUBSTITUIÇÃO TRIBUTÁRIA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '06' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '06 - OPERAÇÃO TRIBUTÁVEL A ALÍQUOTA ZERO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '07' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '07 - OPERAÇÃO ISENTA DA CONTRIBUIÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '08' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '08 - OPERAÇÃO SEM INCIDÊNCIA DA CONTRIBUIÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '09' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '09 - OPERAÇÃO COM SUSPENSÃO DA CONTRIBUIÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '49' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '49 - OUTRAS OPERAÇÕES DE SAÍDA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '50' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '50 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '51' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '51 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA NÃO-TRIBUTADA NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '52' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '52 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '53' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '53 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '54' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '54 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '55' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '55 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS NÃO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '56' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '56 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO, E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '60' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '60 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '61' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '61 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA NÃO-TRIBUTADA NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '62' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '62 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '63' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '63 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '64' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '64 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '65' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '65 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS NÃO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '66' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '66 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO, E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '67' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '67 - CRÉDITO PRESUMIDO - OUTRAS OPERAÇÕES'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '70' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '70 - OPERAÇÃO DE AQUISIÇÃO SEM DIREITO A CRÉDITO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '71' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '71 - OPERAÇÃO DE AQUISIÇÃO COM ISENÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '72' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '72 - OPERAÇÃO DE AQUISIÇÃO COM SUSPENSÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '73' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '73 - OPERAÇÃO DE AQUISIÇÃO A ALÍQUOTA ZERO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '74' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '74 - OPERAÇÃO DE AQUISIÇÃO SEM INCIDÊNCIA DA CONTRIBUIÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '75' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '75 - OPERAÇÃO DE AQUISIÇÃO POR SUBSTITUIÇÃO TRIBUTÁRIA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '98' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '98 - OUTRAS OPERAÇÕES DE ENTRADA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '99' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (5,17,23,26,37,56) THEN '99 - OUTRAS OPERAÇÕES'
						  
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '01' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '01 - OPERAÇÃO TRIBUTÁVEL COM ALÍQUOTA BÁSICA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '02' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '02 - OPERAÇÃO TRIBUTÁVEL COM ALÍQUOTA DIFERENCIADA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '03' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '03 - OPERAÇÃO TRIBUTÁVEL COM ALÍQUOTA POR UNIDADE DE MEDIDA DE PRODUTO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '04' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '04 - OPERAÇÃO TRIBUTÁVEL MONOFÁSICA - REVENDA A ALÍQUOTA ZERO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '05' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '05 - OPERAÇÃO TRIBUTÁVEL POR SUBSTITUIÇÃO TRIBUTÁRIA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '06' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '06 - OPERAÇÃO TRIBUTÁVEL A ALÍQUOTA ZERO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '07' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '07 - OPERAÇÃO ISENTA DA CONTRIBUIÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '08' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '08 - OPERAÇÃO SEM INCIDÊNCIA DA CONTRIBUIÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '09' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '09 - OPERAÇÃO COM SUSPENSÃO DA CONTRIBUIÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '49' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '49 - OUTRAS OPERAÇÕES DE SAÍDA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '50' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '50 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '51' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '51 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA NÃO-TRIBUTADA NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '52' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '52 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '53' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '53 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '54' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '54 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '55' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '55 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS NÃO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '56' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '56 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO, E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '60' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '60 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '61' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '61 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA NÃO-TRIBUTADA NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '62' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '62 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '63' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '63 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '64' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '64 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '65' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '65 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS NÃO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '66' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '66 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO, E DE EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '67' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '67 - CRÉDITO PRESUMIDO - OUTRAS OPERAÇÕES'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '70' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '70 - OPERAÇÃO DE AQUISIÇÃO SEM DIREITO A CRÉDITO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '71' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '71 - OPERAÇÃO DE AQUISIÇÃO COM ISENÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '72' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '72 - OPERAÇÃO DE AQUISIÇÃO COM SUSPENSÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '73' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '73 - OPERAÇÃO DE AQUISIÇÃO A ALÍQUOTA ZERO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '74' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '74 - OPERAÇÃO DE AQUISIÇÃO SEM INCIDÊNCIA DA CONTRIBUIÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '75' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '75 - OPERAÇÃO DE AQUISIÇÃO POR SUBSTITUIÇÃO TRIBUTÁRIA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '98' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '98 - OUTRAS OPERAÇÕES DE ENTRADA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '99' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (6,18,24,27,38,57) THEN '99 - OUTRAS OPERAÇÕES'
						  
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '1' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (12,13) THEN '1 - Não consta na GIA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '2' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (12,13) THEN '2 - Substituído'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '3' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (12,13) THEN '3 - Substituto'
						  
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = 'N' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (14,22) THEN 'N - NORMAL'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = 'R' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (14,22) THEN 'R - RETIDA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = 'S' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (14,22) THEN 'S - SUBSTITUTA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = 'I' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (14,22) THEN 'I - ISENTA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '1' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (14,22) THEN '1 - EXIGÍVEL'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '2' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (14,22) THEN '2 - NÃO INCIDÊNCIA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '3' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (14,22) THEN '3 - ISENÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '4' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (14,22) THEN '4 - EXPORTAÇÃO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '5' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (14,22) THEN '5 - IMUNIDADE'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '6' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (14,22) THEN '6 - EXIGIBILIDADE SUSPENSA POR DECISÃO JUDICIAL'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '7' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO IN (14,22) THEN '7 - EXIGIBILIDADE SUSPENSA POR PROCESSO ADMINISTRATIVO'
						  
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '1'  AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '1 - TAXI'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '2'  AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '3 - PRODUTOS AGROPECUARIO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '3'  AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '4 - FROTISTA/LOCADORA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '4'  AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '5 - DIPLOMATA/CONSULAR'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '5'  AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '6 - UTILITARIO/MOTO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '6'  AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '7 - SUFRAMA'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '7'  AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '8 - VENDA A ORGAO PUBLICO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '8'  AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '9 - OUTROS'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '9'  AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '10 - DEFICIENTE CONDUTOR (CONVÊNIO ICMS 38/12)'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '10' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '11 - DEFICIENTE NÃO CONDUTOR (CONVÊNIO ICMS 38/12)'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '11' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '12 - ÓRGÃO DE FOMENTO E DESENVOLVIMENTO AGROPECUÁRIO'
						  WHEN CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA = '12' AND CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = 36 AND CTB_EXCECAO_IMPOSTO.TRIBUT_ICMS IN ('20','30','40','41','50','70','90') THEN '16 - OLIMPÍADAS RIO 2016'
						  ELSE CONVERT(CHAR(5),CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA) END AS SITUACAO_TRIBUTARIA,

						  CTB_EXCECAO_IMPOSTO_ITEM.SITUACAO_TRIBUTARIA_MUNICIPAL,
						  CTB_EXCECAO_IMPOSTO_ITEM.TEXTO_LEGAL,
						  CTB_EXCECAO_IMPOSTO_ITEM.CODIGO_ARRECADACAO,
						  CTB_EXCECAO_IMPOSTO_ITEM.VALOR_MIN_ARRECADACAO,
						  CTB_EXCECAO_IMPOSTO_ITEM.VALOR_MAX_ARRECADACAO,
						  CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.VALIDA_VALOR_PARCELA = 1 THEN 'S' ELSE 'N' END AS VALIDA_VALOR_PARCELA,
						  CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.ZERA_VALOR_CONTABIL  = 1 THEN 'S' ELSE 'N' END AS ZERA_VALOR_CONTABIL,
						  CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.ZERA_TAXA_IMPOSTO    = 1 THEN 'S' ELSE 'N' END AS ZERA_TAXA_IMPOSTO,
						  CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.ZERA_BASE_IMPOSTO    = 1 THEN 'S' ELSE 'N' END AS ZERA_BASE_IMPOSTO,
						  CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.ZERA_VALOR_IMPOSTO   = 1 THEN 'S' ELSE 'N' END AS ZERA_VALOR_IMPOSTO,
						  CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.COLUNA_IMP_AGREGADO = 'I' THEN 'I - ISENTO'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COLUNA_IMP_AGREGADO = 'O' THEN 'O - OUTROS'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COLUNA_IMP_AGREGADO = 'B' THEN 'B - OBSERVAÇÃO'
							   ELSE CONVERT(CHAR(5),CTB_EXCECAO_IMPOSTO_ITEM.COLUNA_IMP_AGREGADO) END AS COLUNA_IMP_AGREGADO,
						  CTB_EXCECAO_IMPOSTO_ITEM.CODIGO_HISTORICO, CTB_HIST_PADRAO.HISTORICO_PADRAO,

						  CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.USA_TAB_PRECO_BASE = 1 THEN 'S' ELSE 'N' END AS USA_TAB_PRECO_BASE,
					  
						  CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '01' THEN 'CONTRIBUIÇÃO NÃO-CUMULATIVA APURADA A ALÍQUOTA BÁSICA'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '02' THEN 'CONTRIBUIÇÃO NÃO-CUMULATIVA APURADA A ALÍQUOTA DIFERENCIADAS'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '03' THEN 'CONTRIBUIÇÃO NÃO-CUMULATIVA APURADA A ALÍQUOTA POR UNIDADE DE MEDIDA DE PRODUTO'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '04' THEN 'CONTRIBUIÇÃO NÃO-CUMULATIVA APURADA A ALÍQUOTA BÁSICA - ATIVIDADE IMOBILIÁRIA'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '31' THEN 'CONTRIBUIÇÃO APURADA POR SUBSTITUIÇÃO TRIBUTÁRIA'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '32' THEN 'CONTRIBUIÇÃO APURADA POR SUBSTITUIÇÃO TRIBUTÁRIA - VENDAS À ZONA FRANCA DE MANAUS'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '51' THEN 'CONTRIBUIÇÃO CUMULATIVA APURADA A ALÍQUOTA BÁSICA'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '52' THEN 'CONTRIBUIÇÃO CUMULATIVA APURADA A ALÍQUOTA DIFERENCIADAS'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '53' THEN 'CONTRIBUIÇÃO CUMULATIVA APURADA A ALÍQUOTA POR UNIDADE DE MEDIDA DE PRODUTO'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '54' THEN 'CONTRIBUIÇÃO CUMULATIVA APURADA A ALÍQUOTA - ATIVIDADE IMOBILIÁRIA'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '70' THEN 'CONTRIBUIÇÃO APURADA DA ATIVIDADE IMOBILIÁRIA - RET'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '71' THEN 'CONTRIBUIÇÃO APURADA DE SCP - INCIDÊNCIA NÃO CUMULATIVA'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '72' THEN 'CONTRIBUIÇÃO APURADA DE SCP - INCIDÊNCIA CUMULATIVA'
							   WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA = '99' THEN 'CONTRIBUIÇÃO PARA O PIS/PASEP - FOLHA DE SALÁRIOS'
							   ELSE CONVERT(CHAR(5),CTB_EXCECAO_IMPOSTO_ITEM.COD_CONTRIBUICAO_SOCIAL_APURADA) END AS COD_CONTRIBUICAO_SOCIAL_APURADA,
					 
						 CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '101' THEN 'CRÉDITO VINCULADO À RECEITA TRIBUTADA NO MERCADO INTERNO - ALÍQUOTA BÁSICA'
						      WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '102' THEN 'CRÉDITO VINCULADO À RECEITA TRIBUTADA NO MERCADO INTERNO - ALÍQUOTA DIFERENCIADAS'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '103' THEN 'CRÉDITO VINCULADO À RECEITA TRIBUTADA NO MERCADO INTERNO - ALÍQUOTA POR UNIDADE DE PRODUTOS'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '104' THEN 'CRÉDITO VINCULADO À RECEITA TRIBUTADA NO MERCADO INTERNO - ESTOQUE DE ABERTURA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '105' THEN 'CRÉDITO VINCULADO À RECEITA TRIBUTADA NO MERCADO INTERNO - AQUISIÇÃO EMBALAGENS PARA REVENDA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '106' THEN 'CRÉDITO VINCULADO À RECEITA TRIBUTADA NO MERCADO INTERNO - PRESUMIDO DA AGROINDÚSTRIA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '108' THEN 'CRÉDITO VINCULADO À RECEITA TRIBUTADA NO MERCADO INTERNO - IMPORTAÇÃO'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '109' THEN 'CRÉDITO VINCULADO À RECEITA TRIBUTADA NO MERCADO INTERNO - ATIVIDADE IMOBILIÁRIA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '199' THEN 'CRÉDITO VINCULADO À RECEITA TRIBUTADA NO MERCADO INTERNO - OUTROS'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '201' THEN 'CRÉDITO VINCULADO À RECEITA NÃO TRIBUTADA NO MERCADO INTERNO - ALÍQUOTA BÁSICA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '202' THEN 'CRÉDITO VINCULADO À RECEITA NÃO TRIBUTADA NO MERCADO INTERNO - ALÍQUOTA DIFERENCIADAS'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '203' THEN 'CRÉDITO VINCULADO À RECEITA NÃO TRIBUTADA NO MERCADO INTERNO - ALÍQUOTA POR UNIDADE DE PRODUTOS'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '204' THEN 'CRÉDITO VINCULADO À RECEITA NÃO TRIBUTADA NO MERCADO INTERNO - ESTOQUE DE ABERTURA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '205' THEN 'CRÉDITO VINCULADO À RECEITA NÃO TRIBUTADA NO MERCADO INTERNO - AQUISIÇÃO EMBALAGENS PARA REVENDA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '206' THEN 'CRÉDITO VINCULADO À RECEITA NÃO TRIBUTADA NO MERCADO INTERNO - PRESUMIDO DA AGROINDÚSTRIA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '208' THEN 'CRÉDITO VINCULADO À RECEITA NÃO TRIBUTADA NO MERCADO INTERNO - IMPORTAÇÃO'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '299' THEN 'CRÉDITO VINCULADO À RECEITA NÃO TRIBUTADA NO MERCADO INTERNO - OUTROS'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '301' THEN 'CRÉDITO VINCULADO À RECEITA DE EXPORTAÇÃO - ALÍQUOTA BÁSICA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '302' THEN 'CRÉDITO VINCULADO À RECEITA DE EXPORTAÇÃO - ALÍQUOTA DIFERENCIADAS'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '303' THEN 'CRÉDITO VINCULADO À RECEITA DE EXPORTAÇÃO - ALÍQUOTA POR UNIDADE DE PRODUTOS'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '304' THEN 'CRÉDITO VINCULADO À RECEITA DE EXPORTAÇÃO - ESTOQUE DE ABERTURA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '305' THEN 'CRÉDITO VINCULADO À RECEITA DE EXPORTAÇÃO - AQUISIÇÃO EMBALAGENS PARA REVENDA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '306' THEN 'CRÉDITO VINCULADO À RECEITA DE EXPORTAÇÃO - PRESUMIDO DA AGROINDÚSTRIA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '308' THEN 'CRÉDITO VINCULADO À RECEITA DE EXPORTAÇÃO - IMPORTAÇÃO'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO = '399' THEN 'CRÉDITO VINCULADO À RECEITA DE EXPORTAÇÃO - OUTROS'
							  ELSE CONVERT(CHAR(5),CTB_EXCECAO_IMPOSTO_ITEM.TIPO_CREDITO) END AS TIPO_CREDITO,

						 CTB_EXCECAO_IMPOSTO_ITEM.NATUREZA_RECEITA,
						 CTB_EXCECAO_IMPOSTO_ITEM.EXCECAO_CLASSIF_FISCAL,

						 CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '01' THEN 'AQUISIÇÃO DE BENS PARA REVENDA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '02' THEN 'AQUISIÇÃO DE BENS UTILIZADOS COMO INSUMO'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '03' THEN 'AQUISIÇÃO DE SERVIÇOS UTILIZADOS COMO INSUMO'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '04' THEN 'ENERGIA ELÉTRICA E TÉRMICA, INCLUSIVE SOB A FORMA DE VAPOR'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '05' THEN 'ALUGUÉIS DE PRÉDIOS'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '06' THEN 'ALUGUÉIS DE MÁQUINAS E EQUIPAMENTOS' 
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '07' THEN 'ARMAZENAGEM DE MERCADORIA E FRETE NA OPERAÇÃO DE VENDA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '08' THEN 'CONTRAPRESTAÇÕES DE ARRENDAMENTO MERCANTIL'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '09' THEN 'MÁQUINAS, EQUIPAMENTOS E OUTROS BENS INCORPORADOS AO ATIVO IMOBILIZADO (CRÉDITO SOBRE ENCARGOS DE DEPRECIAÇÃO)'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '10' THEN 'MÁQUINAS, EQUIPAMENTOS E OUTROS BENS INCORPORADOS AO ATIVO IMOBILIZADO (CRÉDITO COM BASE NO VALOR DE AQUISIÇÃO)'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '11' THEN 'AMORTIZAÇÃO E DEPRECIAÇÃO DE EDIFICAÇÕES E BENFEITORIAS EM IMÓVEIS'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '12' THEN 'DEVOLUÇÃO DE VENDAS SUJEITAS À INCIDÊNCIA NÃO-CUMULATIVA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '13' THEN 'OUTRAS OPERAÇÕES COM DIREITO A CRÉDITO'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '14' THEN 'ATIVIDADE DE TRANSPORTE DE CARGAS - SUBCONTRATAÇÃO'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '15' THEN 'ATIVIDADE IMOBILIÁRIA - CUSTO INCORRIDO DE UNIDADE IMOBILIÁRIA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '16' THEN 'ATIVIDADE IMOBILIÁRIA - CUSTO ORÇADO DE UNIDADE NÃO CONCLUÍDA'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '17' THEN 'ATIVIDADE DE PRESTAÇÃO DE SERVIÇOS DE LIMPEZA, CONSERVAÇÃO E MANUTENÇÃO - VALE-TRANSPORTE, VALE-REFEIÇÃO OU VALE-ALIMENTAÇÃO, FARDAMENTO OU UNIFORME'
							  WHEN CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO = '18' THEN 'ESTOQUE DE ABERTURA DE BENS'
							  ELSE CONVERT(CHAR(3),CTB_EXCECAO_IMPOSTO_ITEM.COD_BC_CREDITO) END AS COD_BC_CREDITO, 

					    CTB_EXCECAO_IMPOSTO_ITEM.NUMERO_PROCESSO,
					    CASE WHEN CTB_EXCECAO_IMPOSTO_ITEM.INDICADOR_INCENTIVO = 1 THEN 'S' ELSE 'N' END AS INDICADOR_INCENTIVO

						FROM CTB_EXCECAO_IMPOSTO_ITEM (NOLOCK) CTB_EXCECAO_IMPOSTO_ITEM 
						JOIN (SELECT ID_IMPOSTO, IMPOSTO FROM CTB_LX_IMPOSTO_TIPO (NOLOCK)) CTB_LX_IMPOSTO_TIPO ON CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO = CTB_LX_IMPOSTO_TIPO.ID_IMPOSTO
						JOIN CTB_EXCECAO_IMPOSTO (NOLOCK) CTB_EXCECAO_IMPOSTO ON CTB_EXCECAO_IMPOSTO_ITEM.ID_EXCECAO_IMPOSTO = CTB_EXCECAO_IMPOSTO.ID_EXCECAO_IMPOSTO
						LEFT JOIN CTB_HIST_PADRAO (NOLOCK) CTB_HIST_PADRAO ON CTB_EXCECAO_IMPOSTO_ITEM.CODIGO_HISTORICO = CTB_HIST_PADRAO.CODIGO_HISTORICO
						--WHERE CTB_EXCECAO_IMPOSTO_ITEM.ID_EXCECAO_IMPOSTO = '<<v_ctb_excecao_imposto_00.id_excecao_imposto>>'
			ENDTEXT
			f_select(xExcecaoItem,"CurExecaoItem",ALIAS())
			
			IF USED("v_temp_excecao_item")
				USE IN v_temp_excecao_item
			endif	
			
			SELECT b.* FROM v_ctb_excecao_imposto_00 a JOIN CurExecaoItem b ON a.id_excecao_imposto = b.id_excecao_imposto INTO CURSOR v_temp_excecao_item readwrite
				
			Sele v_temp_excecao_item
			go top
			COPY TO c:\temp\Excecao_Imposto_Item.xls XLS
			
			f_wait()
			
			Sele v_ctb_excecao_imposto_00 
			GO TOP 
			
			MESSAGEBOX("Exportado para: "+CHR(13)+; 
					   "- c:\temp\Excecao_Imposto_Capa "+CHR(13)+;
					   "- c:\temp\Excecao_Imposto_Item ",0+64)
			
		endif
	ENDPROC


ENDDEFINE
*
*-- EndDefine: btn_exportar
**************************************************
