INSERT INTO ANM_TB_BLOQ_FICHA_TECNICA_PA
(PRODUTO, DATA_FINALIZACAO)
SELECT A.PRODUTO, NULL 
	FROM PRODUTOS A
	LEFT JOIN ANM_TB_BLOQ_FICHA_TECNICA_PA B
	ON A.PRODUTO = B.PRODUTO
	WHERE B.PRODUTO IS NULL