

/****** Object:  Table [dbo].[ANM_TB_BLOQ_FICHA_TECNICA_PA]    Script Date: 16/08/2016 19:31:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ANM_TB_BLOQ_FICHA_TECNICA_PA](
	[PRODUTO] [char](12) NOT NULL,
	[DATA_FINALIZACAO] [datetime] NULL,
	[FINALIZA] [bit] NOT NULL,
 CONSTRAINT [PK_ANM_TB_BLOQ_FICHA_TECNICA_PA] PRIMARY KEY CLUSTERED 
(
	[PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ANM_TB_BLOQ_FICHA_TECNICA_PA] ADD  CONSTRAINT [DF_ANM_TB_BLOQ_FICHA_TECNICA_PA_FINALIZA]  DEFAULT ((0)) FOR [FINALIZA]
GO


