

/****** Object:  Table [dbo].[ANM_FICHA_TECNICA_LOG_FINALIZACAO]    Script Date: 16/08/2016 09:45:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ANM_FICHA_TECNICA_LOG_FINALIZACAO](
	[PRODUTO] [char](12) NOT NULL,
	[DATA_FINALIZA_ANTES] [datetime] NULL,
	[FINALIZA_ANTES] [bit] NULL,
	[DATA_FINALIZA_NOVO] [datetime] NULL,
	[FINALIZA_NOVO] [bit] NULL,
	[DATA_HORA_ALTERACAO] [datetime] NULL,
	[USUARIO_LINX] [varchar](240) NOT NULL,
	[NOME_COMPUTADOR] [varchar](30) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


