USE [SOMA]
GO

/****** Object:  StoredProcedure [dbo].[LX_ANM_ATUALIZA_CARTAO_AFINIDADE]    Script Date: 04/05/2016 20:13:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







CREATE PROCEDURE [dbo].[LX_ANM_ATUALIZA_CARTAO_AFINIDADE] @REDE_LOJAS INT,@ARQUIVO_IMPORT_CARTAO_AFINIDADE VARCHAR(400)

AS


-- =================================================================================
-- AUTHOR:		JULIO
-- CREATE DATE: 25-11-2015
-- DESCRIPTION:	ATUALIZA CARTAO AFINIDADE CLIENTES_VAREJO
-- =================================================================================


BEGIN
	
	DECLARE @DATA_IMPORTACAO DATETIME = (SELECT CONVERT(CHAR(8),GETDATE(),112))

			UPDATE A 
			SET CARTAO_AFINIDADE = B.NUMERO_CARTAO , 
				DATA_IMPORT_CARTAO_AFINIDADE = @DATA_IMPORTACAO , 
				ARQUIVO_IMPORT_CARTAO_AFINIDADE = @ARQUIVO_IMPORT_CARTAO_AFINIDADE , 
				TIPO_VAREJO = CASE WHEN LTRIM(RTRIM(ISNULL(B.TIPO_CLIENTE,''))) <> '' AND C.TIPO_VAREJO IS NOT NULL 
				                   THEN UPPER(RTRIM(LTRIM(B.TIPO_CLIENTE))) 
								   ELSE A.TIPO_VAREJO END,
				DATA_PARA_TRANSFERENCIA = GETDATE()				    
			FROM ANM_CLIENTES_VAREJO_DETALHE A
				JOIN #CTB_IMPORTA_CARTAO_CLIENTE B ON A.CPF_CGC = B.CPF  AND A.REDE_LOJAS = @REDE_LOJAS
					LEFT JOIN CLIENTE_VAR_TIPOS C ON RTRIM(LTRIM(B.TIPO_CLIENTE)) = C.TIPO_VAREJO

					

END
















GO


