
/****** Object:  StoredProcedure [dbo].[LX_ANM_COMPRA_SAVE_AFTER]    Script Date: 05/31/2016 17:51:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
















alter PROCEDURE [dbo].[LX_ANM_COMPRA_SAVE_AFTER] @PEDIDO CHAR(8),@STATUS_TELA CHAR(1)
AS


-- =================================================================================
-- AUTHOR:		JULIO
-- CREATE DATE: 25-11-2015
-- DESCRIPTION:	RODA NO OBJETO DA TELA DE PEDIDO DE COMPRAS PA NO METODO SAVE AFTER
-- =================================================================================


BEGIN

	IF @STATUS_TELA = 'I'
	BEGIN
		
		---------- #5 - DATA ENTREGA, LIMITE ENTREGA RETRABALHO TI - 01/06/2016 LUCAS MIRANDA------
		--UPDATE COMPRAS SET CTRL_MULT_ENTREGAS = 0,
		--			       APROVADOR_POR = UPPER(replace(SYSTEM_USER,'ANIMALE\','')),--+' '+LEFT(convert(varchar(10), GETDATE(), 103),6) + Right(Year(GETDATE()),2),
		--				   ANM_FILIAL_MATERIAL = (select VALOR_ATUAL from FX_ANM_PARAMETROS_REDE_LOJAS('ANM_FILIAL_MATERIAL_COMPR')),
		--				   STATUS_APROVACAO = 'A', STATUS_COMPRA = 'A', DATA_APROVACAO = GETDATE(),
		--				   FRETE_A_PAGAR = '1'
		--WHERE PEDIDO = @PEDIDO
		--AND TABELA_FILHA = 'COMPRAS_PRODUTO'
		---------- #5 - DATA ENTREGA, LIMITE ENTREGA RETRABALHO TI - 01/06/2016 LUCAS MIRANDA ------
		
		UPDATE A SET A.FILIAL_A_ENTREGAR = B.FILIAL, A.FILIAL_A_FATURAR = B.FILIAL, A.FILIAL_COBRANCA = B.FILIAL,
		CTRL_MULT_ENTREGAS = 0,
        APROVADOR_POR = UPPER(replace(SYSTEM_USER,'ANIMALE\','')),--+' '+LEFT(convert(varchar(10), GETDATE(), 103),6) + Right(Year(GETDATE()),2),
	    ANM_FILIAL_MATERIAL = (select VALOR_ATUAL from FX_ANM_PARAMETROS_REDE_LOJAS('ANM_FILIAL_MATERIAL_COMPR')),
	    STATUS_APROVACAO = 'A', STATUS_COMPRA = 'A', DATA_APROVACAO = GETDATE(),
	    FRETE_A_PAGAR = '1'
		FROM COMPRAS (NOLOCK) A
		JOIN COMPRAS_PRODUTO (NOLOCK) COMPRAS_PROD
		ON A.PEDIDO = COMPRAS_PROD.PEDIDO
		AND A.TABELA_FILHA = 'COMPRAS_PRODUTO'
		JOIN PRODUTOS PRODUTOS (NOLOCK) 
		ON COMPRAS_PROD.PRODUTO = PRODUTOS.PRODUTO
		--AND PRODUTOS.REDE_LOJAS IN (1,3,4)
		JOIN PRODUCAO_PROGRAMA (NOLOCK) B
		ON A.PROGRAMACAO = B.PROGRAMACAO
		WHERE A.PEDIDO = @PEDIDO
		AND TABELA_FILHA = 'COMPRAS_PRODUTO'



		---------- #5 - DATA ENTREGA, LIMITE ENTREGA RETRABALHO TI - 01/06/2016 LUCAS MIRANDA ------
		--UPDATE A SET ENTREGA = '19600101', LIMITE_ENTREGA = '19600101'
		--FROM COMPRAS_PRODUTO (NOLOCK) A  
		--JOIN COMPRAS (NOLOCK) B
		--ON A.PEDIDO = B.PEDIDO
		--AND B.TABELA_FILHA = 'COMPRAS_PRODUTO'	
		--AND B.TIPO_COMPRA NOT LIKE '%CONSERTO%'	
		--WHERE A.PEDIDO = @PEDIDO
		---------- #5 - DATA ENTREGA, LIMITE ENTREGA RETRABALHO TI - 01/06/2016 LUCAS MIRANDA ------
	END
	
	IF @STATUS_TELA = 'A'
					BEGIN
						UPDATE A SET RESERVA = 0,MATAR_SALDO_RESERVA=1 
						FROM PRODUCAO_RESERVA (NOLOCK) A 
						JOIN COMPRAS (NOLOCK) B
						ON A.ORDEM_PRODUCAO = B.PEDIDO
						AND B.TABELA_FILHA = 'COMPRAS_PRODUTO'
						WHERE ORDEM_PRODUCAO = @PEDIDO
						AND B.ANM_STATUS_ALMOX <> '1-ENVIADO PARA ALMOX'
						AND STATUS_APROVACAO = 'R'
						AND RESERVA > 0


						UPDATE A SET 
						TOT_QTDE_ENTREGAR = B.QTDE_ENTREGAR,
						TOT_VALOR_ENTREGAR = B.VALOR_ENTREGAR 
						FROM COMPRAS (NOLOCK) A JOIN
						(SELECT PEDIDO,
								SUM(QTDE_ENTREGAR) AS QTDE_ENTREGAR,
								SUM(VALOR_ENTREGAR) AS VALOR_ENTREGAR  
						 FROM COMPRAS_PRODUTO (NOLOCK) WHERE PEDIDO = @PEDIDO
						 GROUP BY PEDIDO ) B
						 ON A.PEDIDO = B.PEDIDO
						 AND A.TABELA_FILHA = 'COMPRAS_PRODUTO'	
						 WHERE TOT_QTDE_ENTREGAR <> B.QTDE_ENTREGAR OR
							   TOT_VALOR_ENTREGAR <> B.VALOR_ENTREGAR
					END

END














GO


