

/****** Object:  View [dbo].[WANM_ESTOQUE_MAT_DISPONIVEL_FILIAL]    Script Date: 06/09/2016 15:03:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- VIEW UTILIZADA PARA A TELA GS0005 - LUCAS MIRANDA 08/09/2016
CREATE VIEW [dbo].[WANM_ESTOQUE_MAT_DISP_PEDIDO_PA] AS 

SELECT B.PEDIDO,b.ANM_FILIAL_MATERIAL AS FILIAL,MATERIAL,COR_MATERIAL,SUM(RESERVA) AS RESERVA FROM PRODUCAO_RESERVA (NOLOCK) A 
							JOIN COMPRAS (NOLOCK) B
							ON A.ORDEM_PRODUCAO = B.PEDIDO
						WHERE RESERVA > 0 AND MATAR_SALDO_RESERVA = 0 AND STATUS_COMPRA <> 'C' 
						  AND B.TABELA_FILHA = 'COMPRAS_PRODUTO' AND ANM_STATUS_ALMOX = '1-ENVIADO PARA ALMOX'	 --AND 1=2 
						GROUP BY B.PEDIDO,b.ANM_FILIAL_MATERIAL,MATERIAL,COR_MATERIAL					 
	




















GO


