

/****** Object:  View [dbo].[WANM_ESTOQUE_MAT_DISPONIVEL_FILIAL]    Script Date: 06/09/2016 15:03:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- VIEW UTILIZADA PARA A TELA GS0005 - LUCAS MIRANDA 08/09/2016
CREATE VIEW [dbo].[WANM_ESTOQUE_MAT_DISP_PEDIDO_OS] AS 

SELECT A.ORDEM_PRODUCAO, C.ORDEM_SERVICO, CASE WHEN C.Filial='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE C.FILIAL END FILIAL,
						MATERIAL,COR_MATERIAL,SUM(RESERVA) RESERVA  FROM PRODUCAO_RESERVA  (NOLOCK)A				
						JOIN (SELECT DISTINCT ORDEM_SERVICO, ORDEM_PRODUCAO FROM PRODUCAO_OS_TAREFAS (NOLOCK)) B
						ON A.ORDEM_PRODUCAO = B.ORDEM_PRODUCAO
							JOIN (SELECT DISTINCT FILIAL,ORDEM_SERVICO, ANM_STATUS_ALMOX FROM PRODUCAO_ORDEM_SERVICO (NOLOCK)) C
							ON B.ORDEM_SERVICO = C.ORDEM_SERVICO					
					 WHERE C.ANM_STATUS_ALMOX = '1-ENVIADO PARA ALMOX'			----
					 AND A.ANM_RESERVA_ALMOX = 1 AND RESERVA > 0 
					 GROUP BY A.ORDEM_PRODUCAO, C.ORDEM_SERVICO,
					 CASE WHEN C.Filial='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE C.FILIAL END,
					 MATERIAL,COR_MATERIAL						 
	




















GO


