

/****** Object:  View [dbo].[WANM_ESTOQUE_MAT_DISPONIVEL_FILIAL]    Script Date: 06/09/2016 15:03:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- VIEW UTILIZADA PARA A TELA GS0005 - LUCAS MIRANDA 08/09/2016
CREATE VIEW [dbo].[WANM_ESTOQUE_MAT_DISP_PEDIDO_MP] AS 

SELECT b.PEDIDO,CASE WHEN FILIAL_A_ENTREGAR='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE FILIAL_A_ENTREGAR END FILIAL, --FILIAL_A_ENTREGAR FILIAL,
				            MATERIAL,COR_MATERIAL,SUM(RESERVA) AS RESERVA FROM PRODUCAO_RESERVA (NOLOCK) A 
							JOIN COMPRAS (NOLOCK) B
							ON A.ORDEM_PRODUCAO = B.PEDIDO
						WHERE RESERVA > 0 AND MATAR_SALDO_RESERVA = 0 AND STATUS_COMPRA <> 'C'  --AND 1=2 
						AND B.TABELA_FILHA = 'COMPRAS_MATERIAL'
						GROUP BY b.PEDIDO,CASE WHEN FILIAL_A_ENTREGAR='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE FILIAL_A_ENTREGAR END, --FILIAL_A_ENTREGAR,
						MATERIAL,COR_MATERIAL

















GO


