

/****** Object:  View [dbo].[WANM_ESTOQUE_MAT_DISPONIVEL_FILIAL]    Script Date: 06/09/2016 15:03:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- LUCAS MIRANDA - 
-- QUALQUER ALTERAÇÃO ABAIXO VERIFICAR TAMBEM NAS VIEWS, POR CAUSA DA TELA GS0005 - CONSULTA DE ESTOQUE DISPONIVEL:
-- WANM_ESTOQUE_MAT_DISP_PEDIDO_PILOT
-- WANM_ESTOQUE_MAT_DISP_PEDIDO_OS
-- WANM_ESTOQUE_MAT_DISP_PEDIDO_PA
-- WANM_ESTOQUE_MAT_DISP_PEDIDO_MP


alter VIEW [dbo].[WANM_ESTOQUE_MAT_DISPONIVEL_FILIAL] AS 

SELECT 
FIL.FILIAL,

A.MATERIAL,A.COR_MATERIAL,
ISNULL(B.QTDE_ESTOQUE,0) AS QTDE_ESTOQUE,
SUM(ISNULL(C.RESERVA,0)) AS QTDE_EM_RESERVA,
SUM(ISNULL(F.RESERVA,0)) AS QTDE_EM_RESERVA_COMPRAS,
SUM(ISNULL(D.QTDE_ENTREGAR,0)) AS QTDE_PEDIDO_PILOTAGEM,
SUM(ISNULL(E.RESERVA,0)) AS QTDE_COMPRAS_BENEF, 
ISNULL(B.QTDE_ESTOQUE,0) - SUM(ISNULL(C.RESERVA,0)) - SUM(ISNULL(D.QTDE_ENTREGAR,0)) - SUM(ISNULL(E.RESERVA,0))- SUM(ISNULL(F.RESERVA,0)) AS QTDE_ESTOQUE_DISP 

FROM FILIAIS FIL
LEFT JOIN 
MATERIAIS_CORES (NOLOCK) A ON 1=1

	LEFT JOIN ( SELECT CASE WHEN FILIAL='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE FILIAL END FILIAL , --FILIAL,
					MATERIAL,COR_MATERIAL,SUM(QTDE_ESTOQUE) AS QTDE_ESTOQUE 
					FROM  ESTOQUE_MATERIAIS (NOLOCK)	
								---- QTDE EM ESTOQUE NA DISTRIBUIDORA							----
				--WHERE 
				--( FILIAL = (SELECT DBO.FX_ANM_PARAMETRO_USER('ANM_FILIAL_ARMAZEM') ) )  AND 
				      --QTDE_ESTOQUE > 0 
				      --WHERE MATERIAL = '01010047' AND COR_MATERIAL = '0003' --AND A.FILIAL= 'FABULA - MATRIZ'
				GROUP BY  CASE WHEN FILIAL='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE FILIAL END, --FILIAL,
				MATERIAL,COR_MATERIAL ) B
	ON A.MATERIAL = B.MATERIAL AND A.COR_MATERIAL = B.COR_MATERIAL  
		AND FIL.FILIAL = B.FILIAL
		
		--- RESERVAS DE OS ENVIADAS PARA ALMOX ---
		LEFT JOIN  ( SELECT CASE WHEN C.Filial='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE C.FILIAL END FILIAL, --C.FILIAL,
						MATERIAL,COR_MATERIAL,SUM(RESERVA) RESERVA  FROM PRODUCAO_RESERVA  (NOLOCK)A				---- QTDE EM RESERVA ( ORDEM DE SERVIÇO E PEDIDO DE PILOTAGEM ) ----
						JOIN (SELECT DISTINCT ORDEM_SERVICO, ORDEM_PRODUCAO FROM PRODUCAO_OS_TAREFAS (NOLOCK)) B
						ON A.ORDEM_PRODUCAO = B.ORDEM_PRODUCAO
							---- SALDO DO ESTOQUE DIMINUINDO A RESERVA DA OS QUE ESTA SENDO ANALISADA --  05-01-2014 --
							JOIN (SELECT DISTINCT FILIAL,ORDEM_SERVICO, ANM_STATUS_ALMOX FROM PRODUCAO_ORDEM_SERVICO (NOLOCK)) C
							ON B.ORDEM_SERVICO = C.ORDEM_SERVICO					
							---- SALDO DO ESTOQUE DIMINUINDO A RESERVA DA OS QUE ESTA SENDO ANALISADA --  05-01-2014 --
					 WHERE C.ANM_STATUS_ALMOX = '1-ENVIADO PARA ALMOX'			---- FILTRA SOMENTE OS ENVIADA PARA ALMOX E STATUS = SEPARA		----
					 AND A.ANM_RESERVA_ALMOX = 1 AND RESERVA > 0 
					 GROUP BY CASE WHEN C.Filial='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE C.FILIAL END, --C.FILIAL,
					 MATERIAL,COR_MATERIAL) C					 
		ON A.MATERIAL = C.MATERIAL AND A.COR_MATERIAL = C.COR_MATERIAL AND B.FILIAL = C.FILIAL
			
			--- RESERVA DE PEDIDOS DE PILOTAGEM EMITIDOS ATRAVÉS DA TELA DE PEDIDOS DE PILOTAGEM ---
			LEFT JOIN ( SELECT CASE WHEN FILIAL_DIGITACAO='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE FILIAL_DIGITACAO END AS FILIAL, -- FILIAL_DIGITACAO AS FILIAL,
							MATERIAL,
							COR_MATERIAL,SUM(QTDE_ENTREGAR) QTDE_ENTREGAR FROM VENDAS  (NOLOCK) A						---- QTDE EM RESERVA DE PEDIDOS DE PILOTAGENS					----
							JOIN VENDAS_MATERIAL  (NOLOCK) B
							ON A.PEDIDO = B.PEDIDO
						WHERE A.STATUS = 'A' AND B.QTDE_ENTREGAR > 0 
						  --AND FILIAL = (SELECT DBO.FX_ANM_PARAMETRO_USER('ANM_FILIAL_ARMAZEM') )
						GROUP BY CASE WHEN FILIAL_DIGITACAO='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE FILIAL_DIGITACAO END , --FILIAL_DIGITACAO,
						MATERIAL,COR_MATERIAL ) D								----					
			ON A.MATERIAL = D.MATERIAL AND A.COR_MATERIAL = D.COR_MATERIAL AND B.FILIAL = D.FILIAL
				
				--- RESERVA DE MATERIAL PARA SER BENEFICIADO NOS PEDIDOS DE COMPRAS DO OPERACIONAL ---
				LEFT JOIN ( SELECT CASE WHEN FILIAL_A_ENTREGAR='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE FILIAL_A_ENTREGAR END FILIAL, --FILIAL_A_ENTREGAR FILIAL,
				            MATERIAL,COR_MATERIAL,SUM(RESERVA) AS RESERVA FROM PRODUCAO_RESERVA (NOLOCK) A 
							JOIN COMPRAS (NOLOCK) B
							ON A.ORDEM_PRODUCAO = B.PEDIDO
						WHERE RESERVA > 0 AND MATAR_SALDO_RESERVA = 0 AND STATUS_COMPRA <> 'C'  --AND 1=2 
						AND B.TABELA_FILHA = 'COMPRAS_MATERIAL'
						GROUP BY CASE WHEN FILIAL_A_ENTREGAR='SOMA FABRICA FARM SC' THEN 'FABRICA SOMA FARM' ELSE FILIAL_A_ENTREGAR END, --FILIAL_A_ENTREGAR,
						MATERIAL,COR_MATERIAL ) E											
				ON A.MATERIAL = E.MATERIAL AND A.COR_MATERIAL = E.COR_MATERIAL AND B.FILIAL = E.FILIAL
				
				--- RESERVA DE MATERIAL PARA SER BENEFICIADO NOS PEDIDOS DE COMPRAS DE PA ---
				LEFT JOIN ( SELECT b.ANM_FILIAL_MATERIAL AS FILIAL,MATERIAL,COR_MATERIAL,SUM(RESERVA) AS RESERVA FROM PRODUCAO_RESERVA (NOLOCK) A 
							JOIN COMPRAS (NOLOCK) B
							ON A.ORDEM_PRODUCAO = B.PEDIDO
						WHERE RESERVA > 0 AND MATAR_SALDO_RESERVA = 0 AND STATUS_COMPRA <> 'C' 
						  AND B.TABELA_FILHA = 'COMPRAS_PRODUTO' AND ANM_STATUS_ALMOX = '1-ENVIADO PARA ALMOX'	 --AND 1=2 
						GROUP BY b.ANM_FILIAL_MATERIAL,MATERIAL,COR_MATERIAL ) F											
				ON A.MATERIAL = F.MATERIAL AND A.COR_MATERIAL = F.COR_MATERIAL AND B.FILIAL = F.FILIAL
						
GROUP BY FIL.FILIAL,A.MATERIAL,A.COR_MATERIAL,B.QTDE_ESTOQUE						 
	




















GO


