
/****** Object:  View [dbo].[WANM_BALANCETE_FINANCEIRO]    Script Date: 15/09/2016 10:53:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

---- AUTOR: LUCAS MIRANDA
---- DATA: 16/09/2016
---- VIEW UTILIZADA PARA A TELA GS0007 E LINXWEB




ALTER VIEW [dbo].[WANM_TOTAL_PEDIDO_VENDA_CLIENTES] AS 

SELECT REDE_LOJAS, COLECAO, COD_CLIENTE, SUM(VALOR_ORIGINAL) AS LIMITE_ORIGINAL FROM
		(
		SELECT LEFT(B.REDE_LOJAS,1) AS REDE_LOJAS, A.COLECAO, C.COD_CLIENTE, SUM(TOT_VALOR_ORIGINAL) AS VALOR_ORIGINAL
		FROM VENDAS (NOLOCK) A
		JOIN FILIAIS (NOLOCK) B
		ON A.FILIAL = B.FILIAL
		JOIN CLIENTES_ATACADO (NOLOCK) C
		ON A.CLIENTE_ATACADO = C.CLIENTE_ATACADO
		WHERE A.APROVACAO IN ('A','E')
		GROUP BY LEFT(B.REDE_LOJAS,1), A.COLECAO, C.COD_CLIENTE
		UNION ALL
		select LEFT(B.REDE_LOJAS,1) AS REDE_LOJAS, A.COLECAO, C.COD_CLIENTE, SUM(TOT_VALOR_ORIGINAL) AS VALOR_ORIGINAL  
		from vendas_lote A
		JOIN FILIAIS (NOLOCK) B
		ON A.FILIAL = B.FILIAL
		JOIN CLIENTES_ATACADO (NOLOCK) C
		ON A.CLIENTE_ATACADO = C.CLIENTE_ATACADO
		GROUP BY LEFT(B.REDE_LOJAS,1), A.COLECAO, C.COD_CLIENTE
		) A
GROUP BY REDE_LOJAS, COLECAO, COD_CLIENTE






GO


